[package]
name = "rust_game_2d"
version = "0.1.0"
authors = ["hiro <nhiro3303@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.2"
